-- Migration 010: Promotions, Bonus, Referral, Loyalty & CRM Campaign Engine

-- 1. PROMOTIONS TABLE
CREATE TABLE IF NOT EXISTS promotions (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  code VARCHAR(64) UNIQUE NOT NULL,
  type VARCHAR(32) NOT NULL, -- DEPOSIT_BONUS | FREE_BET | CASHBACK | REFERRAL | LOYALTY
  status VARCHAR(32) DEFAULT 'ACTIVE', -- DRAFT | ACTIVE | PAUSED | EXPIRED | CLOSED
  budget NUMERIC(14,2) DEFAULT 100000.00,
  used_budget NUMERIC(14,2) DEFAULT 0.00,
  max_reward NUMERIC(14,2) DEFAULT 5000.00,
  per_user_limit INT DEFAULT 1,
  min_odds NUMERIC(6,2) DEFAULT 1.50,
  min_stake NUMERIC(14,2) DEFAULT 100.00,
  wagering_multiplier NUMERIC(6,2) DEFAULT 5.0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP WITH TIME ZONE
);

-- 2. USER BONUSES TABLE
CREATE TABLE IF NOT EXISTS user_bonuses (
  id VARCHAR(64) PRIMARY KEY,
  user_id VARCHAR(64) NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  promotion_id VARCHAR(64) NOT NULL REFERENCES promotions(id) ON DELETE CASCADE,
  bonus_amount NUMERIC(14,2) NOT NULL,
  wagering_required NUMERIC(14,2) NOT NULL,
  wagering_completed NUMERIC(14,2) DEFAULT 0.00,
  status VARCHAR(32) DEFAULT 'ACTIVE', -- ACTIVE | COMPLETED | EXPIRED | REVOKED
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_user_bonuses_active ON user_bonuses(user_id, status);

-- 3. REFERRALS TABLE
CREATE TABLE IF NOT EXISTS referrals (
  id VARCHAR(64) PRIMARY KEY,
  referrer_user_id VARCHAR(64) NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  referred_user_id VARCHAR(64) NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  referral_code VARCHAR(64) NOT NULL,
  status VARCHAR(32) DEFAULT 'REGISTERED', -- REGISTERED | FRAUD_REVIEW | QUALIFIED | REWARDED | REJECTED
  reward_amount NUMERIC(14,2) DEFAULT 500.00,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unq_referred_user UNIQUE(referred_user_id)
);

-- 4. USER LOYALTY TABLE
CREATE TABLE IF NOT EXISTS user_loyalty (
  user_id VARCHAR(64) PRIMARY KEY REFERENCES users(user_id) ON DELETE CASCADE,
  points NUMERIC(14,2) DEFAULT 0.00,
  tier VARCHAR(32) DEFAULT 'BRONZE', -- BRONZE | SILVER | GOLD | PLATINUM
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. CRM CAMPAIGNS TABLE
CREATE TABLE IF NOT EXISTS crm_campaigns (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  segment VARCHAR(64) NOT NULL,
  channel VARCHAR(32) DEFAULT 'IN_APP',
  message TEXT NOT NULL,
  status VARCHAR(32) DEFAULT 'ACTIVE',
  sent_count INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
