-- Migration 014: Production Operations, Observability, Disaster Recovery & DevOps Engine

-- 1. PRODUCTION INCIDENTS TABLE (SEV-1 to SEV-4 Model)
CREATE TABLE IF NOT EXISTS incidents (
  id VARCHAR(64) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  severity VARCHAR(16) NOT NULL, -- SEV-1 | SEV-2 | SEV-3 | SEV-4
  service VARCHAR(64) NOT NULL,
  status VARCHAR(32) DEFAULT 'OPEN', -- OPEN | INVESTIGATING | MITIGATING | RESOLVED | POSTMORTEM
  root_cause TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  resolved_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_incidents_status ON incidents(status, severity);

-- 2. PRODUCTION CHANGE MANAGEMENT LOG TABLE
CREATE TABLE IF NOT EXISTS production_changes (
  id VARCHAR(64) PRIMARY KEY,
  version VARCHAR(32) NOT NULL,
  change_type VARCHAR(32) NOT NULL, -- DEPLOYMENT | CONFIG | MIGRATION | FEATURE_FLAG
  description TEXT NOT NULL,
  actor VARCHAR(128) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. BACKUP LOG & RESTORE TEST AUDIT TABLE
CREATE TABLE IF NOT EXISTS backups_log (
  id VARCHAR(64) PRIMARY KEY,
  backup_type VARCHAR(32) NOT NULL, -- FULL_DUMP | WAL_ARCHIVE | RESTORE_TEST
  status VARCHAR(32) DEFAULT 'SUCCESS', -- SUCCESS | FAILED
  size_bytes BIGINT DEFAULT 0,
  duration_ms INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
