/** Public error codes returned by API Explorer. Never include stack traces. */
export const ERROR_CODES = {
  NOT_CONFIGURED: 'NOT_CONFIGURED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  TIMEOUT: 'TIMEOUT',
  RATE_LIMITED: 'RATE_LIMITED',
  PROVIDER_UNAVAILABLE: 'PROVIDER_UNAVAILABLE',
  INVALID_RESPONSE: 'INVALID_RESPONSE',
  NETWORK_ERROR: 'NETWORK_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  NOT_TESTABLE: 'NOT_TESTABLE',
  MOCK_ONLY: 'MOCK_ONLY',
  UNKNOWN_API: 'NOT_FOUND',
};

export const SLOW_MS_DEFAULT = Math.max(250, parseInt(process.env.API_EXPLORER_SLOW_MS, 10) || 2000);
