/**
 * API Explorer registry — canonical metadata for every known integration.
 * Test handlers are referenced by id and loaded lazily so listing APIs
 * does not execute network calls.
 */

export const API_CATEGORIES = [
  { id: 'INTERNAL', label: 'Internal APIs' },
  { id: 'SPORTS_DATA', label: 'Sports Data APIs' },
  { id: 'ODDS', label: 'Odds APIs' },
  { id: 'PAYMENTS', label: 'Payment APIs' },
  { id: 'KYC', label: 'KYC APIs' },
  { id: 'AUTHENTICATION', label: 'Authentication APIs' },
  { id: 'EMAIL', label: 'Email APIs' },
  { id: 'SMS', label: 'SMS APIs' },
  { id: 'INFRASTRUCTURE', label: 'Database / Infrastructure' },
  { id: 'WEBHOOKS', label: 'Webhooks' },
  { id: 'OTHER', label: 'Other Integrations' },
];

/** @typedef {'SAFE_TEST'|'MOCK_SAMPLE'|'CONFIG_ONLY'|'NOT_TESTABLE'} FetchMode */

function api(entry) {
  return {
    type: 'EXTERNAL',
    testable: true,
    fetchMode: 'SAFE_TEST',
    includeInRefreshAll: false,
    includeInPeriodic: false,
    timeout: 10000,
    method: 'GET',
    endpoint: null,
    requiresConfig: [],
    configFields: [],
    mock: false,
    unused: false,
    legacy: false,
    ...entry,
  };
}

export const API_REGISTRY = [
  // ── Internal ──
  api({
    id: 'internal-health',
    name: 'System Health',
    category: 'INTERNAL',
    provider: 'BetKing',
    type: 'INTERNAL',
    description: 'Process health: PostgreSQL, Redis, outbox',
    baseUrl: '/health',
    endpoint: '/health',
    handler: 'internal-health',
    includeInRefreshAll: true,
    includeInPeriodic: false,
  }),
  api({
    id: 'internal-liveness',
    name: 'Liveness Probe',
    category: 'INTERNAL',
    provider: 'BetKing',
    type: 'INTERNAL',
    description: 'Kubernetes/process liveness',
    baseUrl: '/liveness',
    endpoint: '/health/live',
    handler: 'internal-liveness',
    includeInRefreshAll: true,
  }),
  api({
    id: 'internal-readiness',
    name: 'Readiness Probe',
    category: 'INTERNAL',
    provider: 'BetKing',
    type: 'INTERNAL',
    description: 'Public readiness (no internal queue depths)',
    baseUrl: '/readiness',
    endpoint: '/readiness',
    handler: 'internal-readiness',
    includeInRefreshAll: true,
  }),
  api({
    id: 'internal-live-scores-cache',
    name: 'Live Scores Cache',
    category: 'INTERNAL',
    provider: 'Aggregator',
    type: 'INTERNAL',
    description: 'Read-only aggregator cache. Does not force provider refresh.',
    baseUrl: '/api',
    endpoint: '/api/live-scores',
    handler: 'live-scores-cache',
    includeInRefreshAll: true,
  }),
  api({
    id: 'internal-auth',
    name: 'Auth API',
    category: 'INTERNAL',
    provider: 'BetKing',
    type: 'INTERNAL',
    description: 'User authentication routes',
    baseUrl: '/api/auth',
    endpoint: '/api/auth',
    handler: 'auth-required',
    fetchMode: 'CONFIG_ONLY',
    includeInRefreshAll: true,
  }),
  api({
    id: 'internal-bets',
    name: 'Bets API',
    category: 'INTERNAL',
    provider: 'BetKing',
    type: 'INTERNAL',
    description: 'Bet placement and registry — mutations excluded from Explorer',
    baseUrl: '/api',
    endpoint: '/api/bets',
    handler: 'not-testable',
    testable: true,
    fetchMode: 'NOT_TESTABLE',
    includeInRefreshAll: false,
  }),
  api({
    id: 'internal-wallet',
    name: 'Wallet API',
    category: 'INTERNAL',
    provider: 'BetKing',
    type: 'INTERNAL',
    description: 'Wallet and ledger — mutations excluded from Explorer',
    baseUrl: '/api',
    endpoint: '/api/wallet',
    handler: 'not-testable',
    fetchMode: 'NOT_TESTABLE',
    includeInRefreshAll: false,
  }),
  api({
    id: 'internal-admin',
    name: 'Admin API',
    category: 'INTERNAL',
    provider: 'BetKing',
    type: 'INTERNAL',
    description: 'Admin Control Center. Authentication required; tokens never displayed.',
    baseUrl: '/api/admin',
    endpoint: '/api/admin',
    handler: 'auth-required',
    fetchMode: 'CONFIG_ONLY',
    includeInRefreshAll: true,
  }),

  // ── Sports ──
  api({
    id: 'cricbuzz',
    name: 'Cricbuzz',
    category: 'SPORTS_DATA',
    provider: 'Cricbuzz',
    description: 'Cricket match and live score scraper (cricbuzz.com). Registry RapidAPI URL is unused.',
    baseUrl: 'https://www.cricbuzz.com',
    endpoint: '/cricket-match/live-scores',
    handler: 'cricbuzz',
    requiresConfig: [],
    timeout: 10000,
  }),
  api({
    id: 'crex',
    name: 'CREX',
    category: 'SPORTS_DATA',
    provider: 'CREX',
    description: 'Cricket live scores from crex.com live-score HTML',
    baseUrl: 'https://crex.com',
    endpoint: '/',
    handler: 'crex',
    timeout: 10000,
  }),
  api({
    id: 'fancode',
    name: 'FanCode',
    category: 'SPORTS_DATA',
    provider: 'FanCode',
    description: 'FanCode live scores via page __INIT_STATE__',
    baseUrl: 'https://www.fancode.com',
    endpoint: '/',
    handler: 'fancode',
    timeout: 10000,
  }),
  api({
    id: 'tencric',
    name: '10Cric',
    category: 'SPORTS_DATA',
    provider: '10Cric',
    description: 'GraphQL live scores against 10cric2026.com',
    baseUrl: 'https://www.10cric2026.com',
    endpoint: '/graphql',
    handler: 'tencric',
    timeout: 10000,
  }),
  api({
    id: 'espn',
    name: 'ESPN',
    category: 'SPORTS_DATA',
    provider: 'ESPN',
    description: 'Public ESPN scoreboard API (no API key)',
    baseUrl: 'https://site.api.espn.com',
    endpoint: '/apis/site/v2/sports/cricket/scoreboard',
    handler: 'espn',
    timeout: 10000,
  }),
  api({
    id: 'flashscore',
    name: 'Flashscore',
    category: 'SPORTS_DATA',
    provider: 'Flashscore',
    description: 'Live scores and results from flashscore.com (soccer, tennis, snooker, cricket, and more)',
    baseUrl: 'https://www.flashscore.com',
    endpoint: '/x/feed',
    handler: 'flashscore',
    timeout: 15000,
  }),
  api({
    id: 'cricketguru',
    name: 'Cricket Guru',
    category: 'SPORTS_DATA',
    provider: 'Cricket Guru',
    description: 'Live cricket scores from cricketguru.com/live-scores',
    baseUrl: 'https://www.cricketguru.com',
    endpoint: '/live-scores',
    handler: 'cricketguru',
    timeout: 12000,
  }),
  api({
    id: 'cricketliveline',
    name: 'Cricket Liveline',
    category: 'SPORTS_DATA',
    provider: 'CRIX',
    description: 'Live cricket scores from cricketliveline.app / crix.live',
    baseUrl: 'https://cricketliveline.app',
    endpoint: '/matches?filter=live',
    handler: 'cricketliveline',
    timeout: 12000,
  }),
  api({
    id: 'iplsrl',
    name: 'IPLSRL Simulator',
    category: 'SPORTS_DATA',
    provider: 'BetKing',
    type: 'INTERNAL',
    description: 'Internal simulated IPL league. No third-party SRL vendor.',
    baseUrl: 'internal://iplsrl',
    endpoint: null,
    handler: 'iplsrl',
    includeInRefreshAll: true,
    implementation: 'INTERNAL_SIM',
  }),
  api({
    id: 'football-mock',
    name: 'Football Provider',
    category: 'SPORTS_DATA',
    provider: 'Football-Data.org (stub)',
    description: 'Hardcoded football fixtures. Comments mention Football-Data.org; no live calls.',
    baseUrl: null,
    handler: 'mock-sport',
    fetchMode: 'MOCK_SAMPLE',
    mock: true,
    sportId: 'football',
  }),
  api({
    id: 'basketball-mock',
    name: 'Basketball Provider',
    category: 'SPORTS_DATA',
    provider: 'Stub',
    description: 'Hardcoded basketball fixtures',
    handler: 'mock-sport',
    fetchMode: 'MOCK_SAMPLE',
    mock: true,
    sportId: 'basketball',
  }),
  api({
    id: 'tennis-mock',
    name: 'Tennis Provider',
    category: 'SPORTS_DATA',
    provider: 'Stub',
    description: 'Hardcoded tennis fixtures',
    handler: 'mock-sport',
    fetchMode: 'MOCK_SAMPLE',
    mock: true,
    sportId: 'tennis',
  }),
  api({
    id: 'hockey-mock',
    name: 'Hockey Provider',
    category: 'SPORTS_DATA',
    provider: 'Stub',
    description: 'Hardcoded hockey fixtures',
    handler: 'mock-sport',
    fetchMode: 'MOCK_SAMPLE',
    mock: true,
    sportId: 'hockey',
  }),
  api({
    id: 'american-football-mock',
    name: 'American Football Provider',
    category: 'SPORTS_DATA',
    provider: 'Stub',
    description: 'Hardcoded NFL-style fixtures',
    handler: 'mock-sport',
    fetchMode: 'MOCK_SAMPLE',
    mock: true,
    sportId: 'american-football',
  }),
  api({
    id: 'formula1-mock',
    name: 'Formula 1 Provider',
    category: 'SPORTS_DATA',
    provider: 'Stub',
    description: 'Hardcoded F1 fixtures',
    handler: 'mock-sport',
    fetchMode: 'MOCK_SAMPLE',
    mock: true,
    sportId: 'formula1',
  }),
  api({
    id: 'sportradar',
    name: 'SportRadar',
    category: 'SPORTS_DATA',
    provider: 'SportRadar',
    description: 'Env placeholder (SPORTS_PROVIDER_URL). Not wired into the live aggregator.',
    baseUrl: 'https://api.sportradar.us',
    handler: 'not-configured',
    testable: true,
    fetchMode: 'NOT_TESTABLE',
    unused: true,
    requiresConfig: ['SPORTS_PROVIDER_API_KEY', 'SPORTS_PROVIDER_URL'],
    configFields: [
      { label: 'API Key', env: 'SPORTS_PROVIDER_API_KEY' },
      { label: 'Provider URL', env: 'SPORTS_PROVIDER_URL' },
    ],
  }),

  // ── Odds ──
  api({
    id: 'odds-engine-v3',
    name: 'OddsEngineV3',
    category: 'ODDS',
    provider: 'BetKing',
    type: 'INTERNAL',
    description: 'Canonical match state → markets → fair odds → margin → OddsSnapshot. Sandbox only.',
    baseUrl: 'internal://odds-engine-v3',
    endpoint: 'generate()',
    method: 'LOCAL',
    handler: 'odds-engine-v3',
    includeInRefreshAll: true,
    includeInPeriodic: false,
    timeout: 5000,
  }),

  // ── Payments ──
  api({
    id: 'razorpay',
    name: 'Razorpay',
    category: 'PAYMENTS',
    provider: 'Razorpay',
    description: 'Deposit orders and refunds. Explorer never creates charges.',
    baseUrl: 'https://api.razorpay.com',
    endpoint: '/v1/orders',
    method: 'GET',
    handler: 'razorpay',
    requiresConfig: ['RAZORPAY_KEY_ID', 'RAZORPAY_KEY_SECRET'],
    configFields: [
      { label: 'Key ID', env: ['RAZORPAY_KEY_ID', 'VITE_RAZORPAY_KEY_ID'] },
      { label: 'Key Secret', env: 'RAZORPAY_KEY_SECRET' },
      { label: 'Webhook Secret', env: 'RAZORPAY_WEBHOOK_SECRET' },
    ],
    includeInRefreshAll: false,
  }),
  api({
    id: 'phonepe-stub',
    name: 'PhonePe',
    category: 'PAYMENTS',
    provider: 'PhonePe',
    description: 'SmartPaymentRouter routing stub only — no PhonePe SDK.',
    handler: 'not-configured',
    fetchMode: 'NOT_TESTABLE',
    mock: true,
    unused: true,
    configFields: [
      { label: 'Merchant ID', env: 'PHONEPE_MERCHANT_ID' },
      { label: 'Salt Key', env: 'PHONEPE_SALT_KEY' },
    ],
  }),
  api({
    id: 'cashfree-payments-stub',
    name: 'Cashfree Payments',
    category: 'PAYMENTS',
    provider: 'Cashfree',
    description: 'SmartPaymentRouter routing stub only — no Cashfree payments SDK.',
    handler: 'not-configured',
    fetchMode: 'NOT_TESTABLE',
    mock: true,
    unused: true,
  }),

  // ── KYC ──
  api({
    id: 'kyc-internal',
    name: 'Internal KYC Engine',
    category: 'KYC',
    provider: 'BetKing',
    type: 'INTERNAL',
    description: 'PAN/Aadhaar format validation and admin review. No external ID API.',
    handler: 'kyc-internal',
    includeInRefreshAll: true,
  }),
  api({
    id: 'kyc-cashfree',
    name: 'Cashfree Secure ID',
    category: 'KYC',
    provider: 'Cashfree',
    description: 'Future PAN/Aadhaar/bank verification. Not integrated.',
    handler: 'kyc-vendor',
    fetchMode: 'CONFIG_ONLY',
    includeInRefreshAll: true,
  }),
  api({
    id: 'kyc-surepass',
    name: 'Surepass',
    category: 'KYC',
    provider: 'Surepass',
    description: 'Future KYC vendor. Not integrated.',
    handler: 'kyc-vendor',
    fetchMode: 'CONFIG_ONLY',
    includeInRefreshAll: true,
  }),
  api({
    id: 'kyc-hyperverge',
    name: 'HyperVerge',
    category: 'KYC',
    provider: 'HyperVerge',
    description: 'Future KYC vendor. Not integrated.',
    handler: 'kyc-vendor',
    fetchMode: 'CONFIG_ONLY',
    includeInRefreshAll: true,
  }),
  api({
    id: 'kyc-signzy',
    name: 'Signzy',
    category: 'KYC',
    provider: 'Signzy',
    description: 'Future KYC vendor. Not integrated.',
    handler: 'kyc-vendor',
    fetchMode: 'CONFIG_ONLY',
    includeInRefreshAll: true,
  }),

  // ── Auth ──
  api({
    id: 'jwt',
    name: 'JWT Auth',
    category: 'AUTHENTICATION',
    provider: 'BetKing',
    type: 'INTERNAL',
    description: 'HS256 access tokens. Secret never returned.',
    handler: 'jwt',
    requiresConfig: ['JWT_SECRET'],
    configFields: [{ label: 'JWT Secret', env: 'JWT_SECRET' }],
    includeInRefreshAll: true,
  }),
  api({
    id: 'google-oauth',
    name: 'Google OAuth',
    category: 'AUTHENTICATION',
    provider: 'Google',
    description: 'Sign-in with Google',
    baseUrl: 'https://accounts.google.com',
    endpoint: '/o/oauth2/v2/auth',
    handler: 'google-oauth',
    requiresConfig: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET'],
    configFields: [
      { label: 'Client ID', env: 'GOOGLE_CLIENT_ID' },
      { label: 'Client Secret', env: 'GOOGLE_CLIENT_SECRET' },
    ],
    includeInRefreshAll: true,
  }),

  // ── Email ──
  api({
    id: 'smtp-primary',
    name: 'SMTP Primary',
    category: 'EMAIL',
    provider: 'Resend',
    description: 'Transactional email (verification, reset). Verify only — no mail sent.',
    handler: 'smtp-primary',
    requiresConfig: ['SMTP_HOST', 'SMTP_USER', 'SMTP_PASSWORD'],
    configFields: [
      { label: 'SMTP Host', env: 'SMTP_HOST' },
      { label: 'SMTP User', env: 'SMTP_USER' },
      { label: 'SMTP Password', env: 'SMTP_PASSWORD' },
    ],
    includeInRefreshAll: false,
  }),
  api({
    id: 'smtp-fallback',
    name: 'SMTP Fallback',
    category: 'EMAIL',
    provider: 'Brevo',
    description: 'Failover SMTP when primary is rate-limited',
    handler: 'smtp-fallback',
    fetchMode: 'CONFIG_ONLY',
    configFields: [
      { label: 'Fallback Host', env: 'SMTP_FALLBACK_HOST' },
      { label: 'Fallback User', env: 'SMTP_FALLBACK_USER' },
      { label: 'Fallback Password', env: 'SMTP_FALLBACK_PASSWORD' },
    ],
    includeInRefreshAll: true,
  }),

  // ── SMS ──
  api({
    id: 'sms-dlt',
    name: 'India DLT SMS',
    category: 'SMS',
    provider: 'DLT',
    description: 'Optional DLT SMS. Gated until email failover is monitored. Explorer never sends SMS.',
    handler: 'sms-dlt',
    fetchMode: 'CONFIG_ONLY',
    configFields: [
      { label: 'API URL', env: 'SMS_DLT_API_URL' },
      { label: 'API Key', env: 'SMS_DLT_API_KEY' },
      { label: 'Sender ID', env: 'SMS_DLT_SENDER_ID' },
    ],
    includeInRefreshAll: true,
  }),
  api({
    id: 'web-push',
    name: 'Web Push',
    category: 'SMS',
    provider: 'Web Push',
    description: 'Optional web push dispatch',
    handler: 'web-push',
    fetchMode: 'CONFIG_ONLY',
    configFields: [
      { label: 'Dispatch URL', env: 'WEB_PUSH_DISPATCH_URL' },
      { label: 'VAPID Public', env: 'WEB_PUSH_VAPID_PUBLIC' },
    ],
    includeInRefreshAll: true,
  }),

  // ── Infra ──
  api({
    id: 'postgres',
    name: 'PostgreSQL',
    category: 'INFRASTRUCTURE',
    provider: 'PostgreSQL',
    type: 'INTERNAL',
    description: 'Primary database connectivity (no credentials returned)',
    handler: 'postgres',
    includeInRefreshAll: true,
    includeInPeriodic: true,
    timeout: 8000,
    configFields: [{ label: 'Database URL', env: 'DATABASE_URL' }],
  }),
  api({
    id: 'redis',
    name: 'Redis',
    category: 'INFRASTRUCTURE',
    provider: 'Redis',
    type: 'INTERNAL',
    description: 'Cache and rate-limit store (no credentials returned)',
    handler: 'redis',
    includeInRefreshAll: true,
    includeInPeriodic: true,
    timeout: 5000,
    configFields: [{ label: 'Redis URL', env: 'REDIS_URL' }],
  }),

  // ── Webhooks ──
  api({
    id: 'razorpay-webhook',
    name: 'Razorpay Webhook',
    category: 'WEBHOOKS',
    provider: 'Razorpay',
    description: 'Inbound payment webhook HMAC verification',
    baseUrl: '/api/webhooks/razorpay',
    endpoint: '/api/webhooks/razorpay',
    method: 'POST',
    handler: 'razorpay-webhook',
    fetchMode: 'CONFIG_ONLY',
    configFields: [{ label: 'Webhook Secret', env: 'RAZORPAY_WEBHOOK_SECRET' }],
    includeInRefreshAll: true,
  }),
  api({
    id: 'developer-webhooks',
    name: 'Developer Outbound Webhooks',
    category: 'WEBHOOKS',
    provider: 'BetKing',
    type: 'INTERNAL',
    description: 'App webhook subscriptions. Destination URLs are not listed.',
    handler: 'developer-webhooks',
    includeInRefreshAll: true,
  }),
];

const BY_ID = new Map(API_REGISTRY.map((a) => [a.id, a]));

export function getApiById(id) {
  return BY_ID.get(String(id)) || null;
}

export function listRegistry() {
  return API_REGISTRY.map((a) => ({ ...a }));
}

export function listSafeRefreshIds() {
  return API_REGISTRY.filter((a) => a.includeInRefreshAll && a.testable).map((a) => a.id);
}

export function listPeriodicIds() {
  return API_REGISTRY.filter((a) => a.includeInPeriodic).map((a) => a.id);
}
