/**
 * Market Definition & Catalogue Model (lib/models/marketDefinition.mjs)
 * Defines canonical market scopes, pricing models, eligibility rules, and settlement metadata.
 */

export const MARKET_SCOPES = {
  MATCH_WINNER: 'MATCH_WINNER',
  TOTAL_MATCH_RUNS: 'TOTAL_MATCH_RUNS',
  TEAM_TOTAL_RUNS: 'TEAM_TOTAL_RUNS',
  INNINGS_TOTAL_RUNS: 'INNINGS_TOTAL_RUNS',
  POWERPLAY_TOTAL: 'POWERPLAY_TOTAL',
  PLAYER_RUNS: 'PLAYER_RUNS',
  TOTAL_SIXES: 'TOTAL_SIXES',
  TOTAL_FOURS: 'TOTAL_FOURS',
  OVER_TOTAL_RUNS: 'OVER_TOTAL_RUNS',
  NEXT_DELIVERY: 'NEXT_DELIVERY',
  NEXT_WICKETS: 'NEXT_WICKETS',
  PARTNERSHIP_TOTAL: 'PARTNERSHIP_TOTAL',
};

export const MARKET_CATALOGUE = [
  {
    key: 'winner',
    scope: MARKET_SCOPES.MATCH_WINNER,
    title: 'Match Winner (incl. super over)',
    category: 'main',
    sports: ['CRICKET', 'SOCCER', 'BASKETBALL', 'TENNIS'],
    pricingModel: 'WINNER_PROBABILITY',
    eligibilityRules: ['PRE_MATCH', 'LIVE_ACTIVE'],
  },
  {
    key: 'match_total_runs',
    scope: MARKET_SCOPES.TOTAL_MATCH_RUNS,
    title: 'Total Match Runs',
    category: 'totals',
    sports: ['CRICKET'],
    pricingModel: 'MATCH_RUNS_DISTRIBUTION',
    eligibilityRules: ['PRE_MATCH', 'LIVE_ACTIVE'],
  },
  {
    key: 'team1_runs',
    scope: MARKET_SCOPES.TEAM_TOTAL_RUNS,
    title: '{team1} Total Runs',
    category: 'totals',
    teamRef: 'team1',
    sports: ['CRICKET'],
    pricingModel: 'TEAM_RUNS_DISTRIBUTION',
    eligibilityRules: ['PRE_MATCH', 'LIVE_TEAM1_ACTIVE'],
  },
  {
    key: 'team2_runs',
    scope: MARKET_SCOPES.TEAM_TOTAL_RUNS,
    title: '{team2} Total Runs',
    category: 'totals',
    teamRef: 'team2',
    sports: ['CRICKET'],
    pricingModel: 'TEAM_RUNS_DISTRIBUTION',
    eligibilityRules: ['PRE_MATCH', 'LIVE_TEAM2_ACTIVE'],
  },
  {
    key: 'powerplay_total',
    scope: MARKET_SCOPES.POWERPLAY_TOTAL,
    title: '1st Innings 6 Over Powerplay Total',
    category: 'over',
    innings: 1,
    sports: ['CRICKET'],
    pricingModel: 'POWERPLAY_RUNS_DISTRIBUTION',
    eligibilityRules: ['PRE_MATCH', 'LIVE_INNINGS_1_POWERPLAY'],
  },
  {
    key: 'match_sixes',
    scope: MARKET_SCOPES.TOTAL_SIXES,
    title: 'Total Match Sixes',
    category: 'totals',
    sports: ['CRICKET'],
    pricingModel: 'POISSON_SIXES',
    eligibilityRules: ['PRE_MATCH', 'LIVE_ACTIVE'],
  },
  {
    key: 'match_fours',
    scope: MARKET_SCOPES.TOTAL_FOURS,
    title: 'Total Match Fours',
    category: 'totals',
    sports: ['CRICKET'],
    pricingModel: 'POISSON_FOURS',
    eligibilityRules: ['PRE_MATCH', 'LIVE_ACTIVE'],
  },
  {
    key: 'first_over_runs',
    scope: MARKET_SCOPES.OVER_TOTAL_RUNS,
    title: '1st Innings 1st Over Total Runs',
    category: 'over',
    innings: 1,
    sports: ['CRICKET'],
    pricingModel: 'OVER_RUNS_DISTRIBUTION',
    eligibilityRules: ['PRE_MATCH', 'LIVE_INNINGS_1_OVER_1'],
  },
];
