/**
 * OddsEngineV3 — Match Lifecycle State Machine
 * 
 * Enforces valid forward lifecycle state progressions for all sports events.
 * Rejects illegal backwards regressions (e.g., SETTLED -> LIVE).
 */

export const MATCH_LIFECYCLE_STATES = Object.freeze({
  SCHEDULED: 'SCHEDULED',
  PRE_MATCH: 'PRE_MATCH',
  LIVE: 'LIVE',
  SUSPENDED: 'SUSPENDED',
  COMPLETED_PENDING_VERIFICATION: 'COMPLETED_PENDING_VERIFICATION',
  SETTLED: 'SETTLED',
  ARCHIVED: 'ARCHIVED',
  CANCELLED: 'CANCELLED',
  ABANDONED: 'ABANDONED',
  VOID: 'VOID',
  POSTPONED: 'POSTPONED',
});

const VALID_TRANSITIONS = {
  [MATCH_LIFECYCLE_STATES.SCHEDULED]: [
    MATCH_LIFECYCLE_STATES.PRE_MATCH,
    MATCH_LIFECYCLE_STATES.LIVE,
    MATCH_LIFECYCLE_STATES.POSTPONED,
    MATCH_LIFECYCLE_STATES.CANCELLED,
  ],
  [MATCH_LIFECYCLE_STATES.PRE_MATCH]: [
    MATCH_LIFECYCLE_STATES.LIVE,
    MATCH_LIFECYCLE_STATES.SUSPENDED,
    MATCH_LIFECYCLE_STATES.POSTPONED,
    MATCH_LIFECYCLE_STATES.CANCELLED,
  ],
  [MATCH_LIFECYCLE_STATES.LIVE]: [
    MATCH_LIFECYCLE_STATES.SUSPENDED,
    MATCH_LIFECYCLE_STATES.COMPLETED_PENDING_VERIFICATION,
    MATCH_LIFECYCLE_STATES.ABANDONED,
    MATCH_LIFECYCLE_STATES.VOID,
  ],
  [MATCH_LIFECYCLE_STATES.SUSPENDED]: [
    MATCH_LIFECYCLE_STATES.LIVE,
    MATCH_LIFECYCLE_STATES.COMPLETED_PENDING_VERIFICATION,
    MATCH_LIFECYCLE_STATES.ABANDONED,
    MATCH_LIFECYCLE_STATES.VOID,
  ],
  [MATCH_LIFECYCLE_STATES.COMPLETED_PENDING_VERIFICATION]: [
    MATCH_LIFECYCLE_STATES.SETTLED,
    MATCH_LIFECYCLE_STATES.VOID,
    MATCH_LIFECYCLE_STATES.ABANDONED,
  ],
  [MATCH_LIFECYCLE_STATES.SETTLED]: [
    MATCH_LIFECYCLE_STATES.ARCHIVED,
  ],
  [MATCH_LIFECYCLE_STATES.ARCHIVED]: [],
  [MATCH_LIFECYCLE_STATES.CANCELLED]: [MATCH_LIFECYCLE_STATES.ARCHIVED],
  [MATCH_LIFECYCLE_STATES.ABANDONED]: [MATCH_LIFECYCLE_STATES.SETTLED, MATCH_LIFECYCLE_STATES.ARCHIVED],
  [MATCH_LIFECYCLE_STATES.VOID]: [MATCH_LIFECYCLE_STATES.ARCHIVED],
  [MATCH_LIFECYCLE_STATES.POSTPONED]: [MATCH_LIFECYCLE_STATES.SCHEDULED, MATCH_LIFECYCLE_STATES.CANCELLED],
};

/**
 * Validates whether a lifecycle state transition is legally permissible.
 */
export function transitionMatchLifecycle({ currentState, nextState, matchId = 'match_01' }) {
  if (currentState === nextState) {
    return { valid: true, currentState, nextState, isNoOp: true };
  }

  const allowedNext = VALID_TRANSITIONS[currentState] || [];
  const isValid = allowedNext.includes(nextState);

  if (!isValid) {
    return {
      valid: false,
      currentState,
      nextState,
      error: `ILLEGAL_LIFECYCLE_TRANSITION: Cannot transition ${currentState} -> ${nextState} for match ${matchId}.`,
      rejectedAt: new Date().toISOString(),
    };
  }

  return {
    valid: true,
    previousState: currentState,
    currentState: nextState,
    transitionedAt: new Date().toISOString(),
  };
}
